# Generated by Django 3.2.7 on 2022-04-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='p_icone',
            field=models.CharField(blank=True, max_length=64, verbose_name="Code de l'icone"),
        ),
        migrations.AlterField(
            model_name='page',
            name='p_type',
            field=models.CharField(choices=[('page', 'Une page'), ('sys', 'Une page interne'), ('lien', 'Un lien'), ('lien_ext', 'Un lien Externe')], default='page', max_length=8, verbose_name='Type de page'),
        ),
    ]
