# Generated by Django 3.2.7 on 2022-11-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220422_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_titre', models.CharField(max_length=128, unique=True, verbose_name='Titre')),
                ('d_titre_slugify', models.CharField(blank=True, editable=False, max_length=128, verbose_name='Titre Slugify')),
                ('d_type', models.CharField(max_length=64, unique=True, verbose_name='Titre')),
                ('d_variable', models.CharField(max_length=64, unique=True, verbose_name='Titre')),
            ],
            options={
                'verbose_name': 'Stocage de données',
                'verbose_name_plural': 'Stocage de données',
                'ordering': ['d_titre'],
            },
        ),
    ]
