# Generated by Django 3.2.7 on 2022-11-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='d_titre',
            field=models.CharField(max_length=128, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='data',
            name='d_titre_slugify',
            field=models.CharField(blank=True, editable=False, max_length=128, verbose_name='Nom Slugify'),
        ),
        migrations.AlterField(
            model_name='data',
            name='d_type',
            field=models.CharField(max_length=64, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='data',
            name='d_variable',
            field=models.CharField(max_length=64, verbose_name='Valeur'),
        ),
    ]
