# Generated by Django 3.2.16 on 2022-12-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221121_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='p_menu_stack',
            field=models.BooleanField(default=False, verbose_name='Regroupé dans le menu'),
        ),
    ]
