# Generated by Django 3.2.16 on 2023-12-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_page_p_menu_stack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speed_Dial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd_titre', models.CharField(max_length=128, unique=True, verbose_name='Titre')),
                ('sd_adresse', models.CharField(max_length=64, verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Speed Dial',
                'verbose_name_plural': 'Speed Dial',
            },
        ),
    ]
