# Generated by Django 3.2.16 on 2023-12-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_speed_dial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speed_dial',
            name='sd_poid',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Poid'),
        ),
        migrations.AlterField(
            model_name='speed_dial',
            name='sd_adresse',
            field=models.CharField(max_length=256, verbose_name='Adresse'),
        ),
    ]
