# Generated by Django 3.2.16 on 2023-12-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20231201_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='speed_dial',
            name='sd_icone',
            field=models.CharField(blank=True, max_length=64, verbose_name="Code de l'icone"),
        ),
    ]
