# Generated by Django 3.2.16 on 2023-12-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_speed_dial_sd_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='speed_dial',
            name='sd_color',
            field=models.CharField(choices=[('primary', 'Bleu'), ('secondary', 'Gris'), ('success', 'Vert'), ('danger', 'Rouge'), ('warning', 'Orange'), ('info', 'Bleu clair'), ('dark', 'Noir'), ('white', 'Blanc')], default='primary', max_length=10, verbose_name='Couleur du cadre'),
        ),
    ]
