# Generated by Django 3.2.16 on 2023-12-22 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_speed_dial_sd_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='p_menu_stack',
        ),
        migrations.AddField(
            model_name='page',
            name='p_menu_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.page'),
        ),
    ]
