# Generated by Django 3.2.23 on 2024-01-18 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20231222_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='p_menu_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.page', verbose_name='Parent'),
        ),
    ]
