# Generated by Django 3.2.23 on 2024-01-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_page_p_menu_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='p_menu_est_parent',
            field=models.BooleanField(default=False, verbose_name='Utilisé comme parent'),
        ),
    ]
