# Generated by Django 3.2.23 on 2024-01-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_page_p_menu_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_nom', models.CharField(blank=True, editable=False, max_length=128, verbose_name='Nom du fichier')),
                ('f_fichier', models.FileField(upload_to='static/uploads/', verbose_name='Fichier')),
            ],
        ),
    ]
