# Generated by Django 3.2.23 on 2024-01-19 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_fichier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fichier',
            options={'ordering': ['f_date'], 'verbose_name': 'Stocage de fichiers', 'verbose_name_plural': 'Stocage de fichiers'},
        ),
        migrations.AddField(
            model_name='fichier',
            name='f_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
