# Generated by Django 3.2.23 on 2024-04-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20240119_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_nom', models.CharField(max_length=128, unique=True, verbose_name='Nom du groupe')),
                ('g_nom_slugify', models.CharField(blank=True, editable=False, max_length=128, verbose_name='Nom Slugify')),
            ],
            options={
                'verbose_name': 'Groupe',
                'verbose_name_plural': 'Groupes',
            },
        ),
    ]
