# Generated by Django 3.2.23 on 2024-04-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_groupe'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupe',
            name='g_description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
