# Generated by Django 3.2.23 on 2024-04-22 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_groupe_g_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='speed_dial',
            name='sd_groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.speed_dial', verbose_name='Groupe'),
        ),
    ]
