# Generated by Django 3.2.23 on 2024-04-22 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_speed_dial_sd_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speed_dial',
            name='sd_groupe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.groupe', verbose_name='Groupe'),
        ),
    ]
