# Generated by Django 3.2.23 on 2024-04-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_speed_dial_sd_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speed_dial',
            name='sd_titre',
            field=models.CharField(max_length=128, verbose_name='Titre'),
        ),
    ]
