# Generated by Django 3.2.23 on 2024-04-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_speed_dial_sd_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='p_groupe',
            field=models.BooleanField(default=False, verbose_name='Afficher les groupes'),
        ),
        migrations.AddField(
            model_name='page',
            name='p_speedial',
            field=models.BooleanField(default=False, verbose_name='Afficher le Speedial'),
        ),
    ]
