# Generated by Django 3.2.23 on 2024-07-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20240423_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='p_proteger',
            field=models.BooleanField(default=False, verbose_name='Disponible que si authentifier'),
        ),
    ]
