# Generated by Django 3.2.23 on 2024-07-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_page_p_proteger'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='p_card_main_panel',
            field=models.CharField(choices=[('def', 'Default'), ('oui', 'Oui'), ('non', 'Non')], default='def', max_length=3, verbose_name='Afficage du cadre central'),
        ),
        migrations.AddField(
            model_name='page',
            name='p_card_right_panel',
            field=models.CharField(choices=[('def', 'Default'), ('oui', 'Oui'), ('non', 'Non')], default='def', max_length=3, verbose_name='Afficage du cadre de droite'),
        ),
    ]
