# Generated by Django 3.2.23 on 2024-07-30 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20240730_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='p_card_main_panel',
            new_name='p_c_card_mp',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='p_card_right_panel',
            new_name='p_c_card_rp',
        ),
    ]
