# Generated by Django 3.2.23 on 2024-07-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20240730_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='p_c_card_mp',
            new_name='c_card_mp',
        ),
        migrations.RenameField(
            model_name='page',
            old_name='p_c_card_rp',
            new_name='c_card_rp',
        ),
    ]
