# Generated by Django 4.2.30 on 2026-04-28 19:30

import core.storage.backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20240730_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='f_fichier',
            field=models.FileField(storage=core.storage.backends.StaticStorage(), upload_to='uploads/', verbose_name='Fichier'),
        ),
    ]
